name: Deploy to rshelopal.site

on:
  push:
    branches: [ main ]

env:
  DEPLOY_HOST: ${{ secrets.DEPLOY_HOST }}
  DEPLOY_USER: ${{ secrets.DEPLOY_USER }}
  DEPLOY_PATH: ${{ secrets.DEPLOY_PATH }}
  DEPLOY_PORT: ${{ secrets.DEPLOY_PORT }}

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Install rsync & sshpass
        run: |
          sudo apt-get update
          sudo apt-get install -y rsync sshpass

      - name: Rsync to server (password auth)
        env:
          SSHPASS: ${{ secrets.DEPLOY_PASSWORD }}
        run: |
          rsync -az --delete \
            --exclude ".git" --exclude ".github" \
            -e "ssh -o StrictHostKeyChecking=no -p ${DEPLOY_PORT:-22} \
                -o PreferredAuthentications=password \
                -o PubkeyAuthentication=no" \
            ./ "${DEPLOY_USER}@${DEPLOY_HOST}:${DEPLOY_PATH}"
